export const INTERNAL_LINKS = {
  appUrl: 'https://summer.fi',
  homepage: '/',
  about: '/about',
  discover: '/discover',
  notFound: '/not-found',
  privacy: '/privacy',
  cookie: '/cookie',
  terms: '/terms',
  security: '/security',
  referrals: '/referrals',
  brand: '/brand',
  borrow: '/borrow',
  multiply: '/multiply',
  earn: '/earn',
  earnDSR: '/earn/dsr',
  ajna: '/ajna',
  ajnaBorrow: '/ajna/borrow',
  ajnaEarn: '/ajna/earn',
  ajnaMultiply: '/ajna/multiply',
  ajnaRewards: '/ajna/rewards',
  findYourDefiProduct: '/earn',
}

export const EXTERNAL_LINKS = {
  // NO ENDING SLASH thank you
  KB: {
    HELP: 'https://kb.summer.fi/help',
    CONTACT: 'https://kb.summer.fi/help/contact-us',
    GETTING_STARTED: 'https://kb.summer.fi/help/getting-started',
    TUTORIALS: 'https://kb.summer.fi/help/tutorials',
    BORROW: 'https://kb.summer.fi/help/borrow',
    DISCOVER: 'https://kb.summer.fi/help/learn-more-about-discover',
    WHAT_IS_MULTIPLY: 'https://kb.summer.fi/help/what-is-multiply',
    WHAT_IS_BORROW: 'https://kb.summer.fi/help/what-is-oasis-borrow',
    WHAT_IS_DPM: 'https://kb.summer.fi/help/what-is-a-smart-defi-account',
    WHAT_IS_PROXY: 'https://kb.summer.fi/help/what-is-a-proxy-contract',
    WHAT_IS_CONSTANT_MULTIPLE: 'https://kb.summer.fi/help/what-is-constant-multiple',
    REFER_A_FRIEND: 'https://kb.summer.fi/help/a-step-by-step-guide-to-refer-a-friend',
    STOP_LOSS: 'https://kb.summer.fi/help/what-is-automated-stop-loss',
    AUTOMATION: 'https://kb.summer.fi/help/automation',
    MINIMUM_VAULT_DEBT_DUST: 'https://kb.summer.fi/help/minimum-vault-debt-dust',
    CONSTANT_MULTIPLE_RISKS:
      'https://kb.summer.fi/help/what-are-the-risks-associated-with-constant-multiple',
    TAKE_PROFIT: 'https://kb.summer.fi/help/what-is-take-profit',
    ORACLE_SECURITY: 'https://kb.summer.fi/help/the-oracle-security-module',
    AUTO_BUY_SELL: 'https://kb.summer.fi/help/what-is-auto-buy-and-auto-sell',
    SETTING_AUTO_BUY: 'https://kb.summer.fi/help/setting-up-auto-buy-for-your-vault',
    SETTING_AUTO_SELL: 'https://kb.summer.fi/help/setting-up-auto-sell-for-your-vault',
    HOW_STOP_LOSS_WORKS: 'https://kb.summer.fi/help/how-does-automated-stop-loss-work',
    WHAT_YOU_SHOULD_KNOW_ABOUT_STETH: 'https://kb.summer.fi/help/what-you-should-know-about-steth',
    STETH_AAVE_V3_EMODE: 'https://kb.summer.fi/help/earn-with-steth-aave-v3-e-mode',
    EARN_DAI_GUNI_MULTIPLY: 'https://kb.summer.fi/help/earn-with-dai-and-g-uni-multiply',
    OPEN_MANAGE_MULTIPLY:
      'https://kb.summer.fi/help/how-to-open-and-manage-your-aave-multiply-position',
    WHAT_IS_SLIPPAGE:
      'https://kb.summer.fi/help/frequently-asked-questions#h_8073651997861662481520644',
    CURATED_TOKEN_LIST: 'https://kb.summer.fi/help/curated-token-list',
    SUPPORTED_COLLATERALS:
      'https://kb.summer.fi/help/collaterals-supported-in-oasis-app#h_126274073291652792840397',
    TOKENS: {
      ETH: 'https://kb.summer.fi/help/collaterals-supported-in-oasis-app#h_126274073291652792840397',
      WSTETH:
        'https://kb.summer.fi/help/collaterals-supported-in-oasis-app#h_274014616431652792856773',
      WBTC: 'https://kb.summer.fi/help/collaterals-supported-in-oasis-app#h_884958393561652792865000',
      RENBTC:
        'https://kb.summer.fi/help/collaterals-supported-in-oasis-app#h_414294869681652792871926',
      LINK: 'https://kb.summer.fi/help/collaterals-supported-in-oasis-app#h_42582440791652792878921',
      MANA: 'https://kb.summer.fi/help/collaterals-supported-in-oasis-app#h_536808626201652802419989',
      MATIC:
        'https://kb.summer.fi/help/collaterals-supported-in-oasis-app#h_615723980991652792924214',
      GUSD: 'https://kb.summer.fi/help/collaterals-supported-in-oasis-app#h_4952663551081652792930397',
      YFI: 'https://kb.summer.fi/help/collaterals-supported-in-oasis-app#h_4996750151161652792936142',
      UNIV2:
        'https://kb.summer.fi/help/collaterals-supported-in-oasis-app#h_1653695461291652792950901',
      CRVV1ETHSTETH:
        'https://kb.summer.fi/help/collaterals-supported-in-oasis-app#h_67885280351652802433065',
    },
    AJNA: 'https://kb.summer.fi/help/ajna',
    SWAP_FAQ: 'https://kb.summer.fi/help/how-to-swap-and-bridge-using-the-lifi-widget',
  },
  BLOG: {
    MAIN: 'https://blog.summer.fi',
    REFERAL_PROGRAM_INFO: 'https://blog.summer.fi/oasis-app-referral-program-is-here',
    VAULT_AFTER_MERGE: 'https://blog.summer.fi/what-to-expect-for-your-vault-after-the-merge',
    EXPANDING_EARN_AAVE_V3: 'https://blog.summer.fi/expanding-earn-with-aave-v3',
    MULTIPLY_FOR_AAVE: 'https://blog.summer.fi/introducing-oasis-multiply-for-aave',
    DSR_RATE_HIKE: 'https://blog.summer.fi/dsr-rate-hike/',
    MAKER_STABILITY_FEE_CHANGES: 'https://blog.summer.fi/major-stability-fee-changes/',
    REBRANDING: 'https://blog.summer.fi/oasis-app-rebrands-to-summer-fi/',
  },
  LEGACY_APP: 'https://legacy.summer.fi',
  AJNA: {
    HOME: 'https://www.ajna.finance/',
  },
  WORKABLE: 'https://oasisapp.workable.com',
  TWITTER: 'https://twitter.com/oasisdotapp',
  DISCORD: 'https://discord.gg/oasisapp',
  GITHUB: 'https://github.com/OasisDEX/oasis-borrow',
  BUG_BOUNTY: 'https://immunefi.com/bounty/oasisapp',
  ETHERSCAN: 'https://etherscan.io',
  ETHTX: 'https://ethtx.info',
  DUNE_ORG_STETHETH_PEG_HISTORY: 'https://dune.com/oasisapp/steth-eth-peg-history',
  METAMASK_12130_ISSUE: 'https://github.com/MetaMask/metamask-extension/issues/12130',
  ETHEREUM_ORG_MERKLING: 'https://blog.ethereum.org/2015/11/15/merkling-in-ethereum',
  WONDERWALL: 'https://www.youtube.com/embed/6hzrDeceEKc',
  LIDO_FI_STETH_LIQUIDITY:
    'https://blog.lido.fi/providing-steth-liquidity-via-curve-to-receive-rewards',
}
