export const INTERNAL_LINKS = {
  appUrl: 'https://summer.fi',
  homepage: '/',
  about: '/about',
  notFound: '/not-found',
  privacy: '/privacy',
  cookie: '/cookie',
  terms: '/terms',
  security: '/security',
  referrals: '/referrals',
  brand: '/brand',
  borrow: '/borrow',
  multiply: '/multiply',
  earn: '/earn',
  earnDSR: '/earn/dsr',
  ajna: '/ajna',
  ajnaBorrow: '/ajna/borrow',
  ajnaEarn: '/ajna/earn',
  ajnaMultiply: '/ajna/multiply',
  ajnaRewards: '/ajna/rewards',
  ajnaPoolFinder: '/ajna/pool-finder',
  ajnaPoolCreator: '/ajna/pool-creator',
  sparkRewards:
    'https://forum.makerdao.com/t/sparkdao-spk-pre-farming-airdrop-general-subdao-farming-overview/21595',
}

export const EXTERNAL_LINKS = {
  // NO ENDING SLASH thank you
  KB: {
    HELP: 'https://docs.summer.fi',
    CONTACT: 'https://docs.summer.fi/get-in-touch/social-media',
    GETTING_STARTED: 'https://docs.summer.fi',
    TUTORIALS: 'https://docs.summer.fi/protocols/maker/tutorials-and-guides',
    BORROW:
      'https://docs.summer.fi/protocols/maker/tutorials-and-guides/how-to-open-a-borrow-vault-with-maker',
    WHAT_IS_MULTIPLY: 'https://docs.summer.fi/products/multiply',
    WHAT_IS_BORROW: 'https://docs.summer.fi/products/borrow',
    WHAT_IS_DPM: 'https://docs.summer.fi/general/what-is-a-smart-defi-account',
    WHAT_IS_PROXY: 'https://docs.summer.fi/protocols/maker/what-is-a-proxy-contract',
    WHAT_IS_CONSTANT_MULTIPLE: 'https://docs.summer.fi/automation/constant-multiple',
    REFER_A_FRIEND: 'https://docs.summer.fi/general/referrals-program/how-to-refer-a-friend',
    STOP_LOSS: 'https://docs.summer.fi/automation/stop-loss',
    AUTOMATION: 'https://docs.summer.fi/automation/general',
    MINIMUM_VAULT_DEBT_DUST: 'https://docs.summer.fi/protocols/maker/key-concepts',
    CONSTANT_MULTIPLE_RISKS:
      'https://docs.summer.fi/automation/constant-multiple#what-are-the-risks-associated-with-constant-multiple',
    TAKE_PROFIT: 'https://docs.summer.fi/automation/take-profit',
    ORACLE_SECURITY: 'https://docs.summer.fi/protocols/maker/key-concepts',
    AUTO_BUY_SELL: 'https://docs.summer.fi/automation/auto-buy-and-auto-sell',
    SETTING_AUTO_BUY: 'https://docs.summer.fi/automation/auto-buy-and-auto-sell/auto-buy',
    SETTING_AUTO_SELL: 'https://docs.summer.fi/automation/auto-buy-and-auto-sell/auto-sell',
    HOW_STOP_LOSS_WORKS: 'https://docs.summer.fi/automation/stop-loss',
    HOW_TRAILING_STOP_LOSS_WORKS: 'https://docs.summer.fi/automation/trailing-stop-loss',
    WHAT_YOU_SHOULD_KNOW_ABOUT_STETH: 'https://docs.summer.fi/products/earn/aave-v2-steth',
    STETH_AAVE_V3_EMODE: 'https://docs.summer.fi/products/earn/aave-v3-steth',
    EARN_DAI_GUNI_MULTIPLY: 'https://docs.summer.fi/products/earn',
    OPEN_MANAGE_MULTIPLY: 'https://docs.summer.fi/protocols/aave/tutorials-and-guides',
    WHAT_IS_SLIPPAGE:
      'https://docs.summer.fi/products/multiply/frequently-asked-questions#h_8073651997861662481520644',
    CURATED_TOKEN_LIST: 'https://docs.summer.fi/general/collaterals-supported-in-summer.fi',
    SUPPORTED_COLLATERALS: 'https://docs.summer.fi/general/collaterals-supported-in-summer.fi',
    TOKENS: {
      ETH: 'https://docs.summer.fi/general/collaterals-supported-in-summer.fi',
      WSTETH: 'https://docs.summer.fi/general/collaterals-supported-in-summer.fi',
      WBTC: 'https://docs.summer.fi/general/collaterals-supported-in-summer.fi',
      RENBTC: 'https://docs.summer.fi/general/collaterals-supported-in-summer.fi',
      LINK: 'https://docs.summer.fi/general/collaterals-supported-in-summer.fi',
      MANA: 'https://docs.summer.fi/general/collaterals-supported-in-summer.fi',
      MATIC: 'https://docs.summer.fi/general/collaterals-supported-in-summer.fi',
      GUSD: 'https://docs.summer.fi/general/collaterals-supported-in-summer.fi',
      YFI: 'https://docs.summer.fi/general/collaterals-supported-in-summer.fi',
      UNIV2: 'https://docs.summer.fi/general/collaterals-supported-in-summer.fi',
    },
    SWAP_FAQ: 'https://docs.summer.fi/general/how-to-swap-and-bridge-using-the-lifi-widget',
    WHAT_IS_SDAI: 'https://docs.summer.fi/products/earn/dai-savings-rate-dsr/whats-sdai',
    WHAT_IS_SDAI_CONVERSION:
      'https://docs.summer.fi/products/earn/dai-savings-rate-dsr/what-is-sdai-conversion',
  },
  BLOG: {
    MAIN: 'https://blog.summer.fi',
    REFERAL_PROGRAM_INFO: 'https://blog.summer.fi/oasis-app-referral-program-is-here',
    VAULT_AFTER_MERGE: 'https://blog.summer.fi/what-to-expect-for-your-vault-after-the-merge',
    EXPANDING_EARN_AAVE_V3: 'https://blog.summer.fi/expanding-earn-with-aave-v3',
    MULTIPLY_FOR_AAVE: 'https://blog.summer.fi/introducing-oasis-multiply-for-aave',
    DSR_RATE_HIKE: 'https://blog.summer.fi/dsr-rate-hike/',
    MAKER_STABILITY_FEE_CHANGES: 'https://blog.summer.fi/major-stability-fee-changes/',
    LEARN: 'https://blog.summer.fi/tag/learn',
    HOW_TO_SET_UP_AUTO_TAKE_PROFIT: 'https://blog.summer.fi/how-to-set-up-auto-take-profit',
    HOW_TO_CHOOSE_THE_RIGHT_PROTOCOL: 'https://blog.summer.fi/how-to-choose-the-right-protocol',
    SELECTING_THE_RIGHT_POSITION_TYPE: 'https://blog.summer.fi/selecting-the-right-position-type',
    SELECTING_THE_RIGHT_PAIR: 'https://blog.summer.fi/selecting-the-right-pair',
    PROTOCOL_TRADEOFFS: 'https://blog.summer.fi/protocol-tradeoffs',
    UNDERSTANDING_YIELD_LOOPS: 'https://blog.summer.fi/understanding-yield-loops',
  },
  DOCS: {
    FAQ: 'https://docs.summer.fi/products/borrow/frequently-asked-questions',
    AJNA: {
      HUB: 'https://docs.summer.fi/protocols/ajna',
      HOW_TO_BORROW:
        'https://docs.summer.fi/protocols/ajna/tutorials-and-guides#how-to-borrow-using-ajna',
      HOW_TO_EARN:
        'https://docs.summer.fi/protocols/ajna/tutorials-and-guides#how-to-earn-using-ajna',
      LIQUIDATIONS:
        'https://docs.summer.fi/protocols/ajna/tutorials-and-guides/how-ajna-liquidations-work',
      RISKS:
        'https://docs.summer.fi/protocols/ajna/tutorials-and-guides/what-are-the-risks-of-lending-in-ajna',
      TOKEN_REWARDS: 'https://docs.summer.fi/protocols/ajna/ajna-token-rewards',
      HOW_TO_PICK_LENDING_PRICE:
        'https://docs.summer.fi/protocols/ajna/tutorials-and-guides/how-to-pick-the-right-level-for-lending',
      HOW_TO_CREATE_A_POOL:
        'https://docs.summer.fi/protocols/ajna/tutorials-and-guides/how-to-create-a-pool-on-ajna',
    },
    MORPHO_BLUE: {
      HUB: 'https://docs.summer.fi/protocols/morpho-blue',
    },
    NAVIGATION: [
      'https://docs.summer.fi/general/get-liquidity-without-selling-your-crypto',
      'https://docs.summer.fi/general/amplify-exposure-to-your-crypto-with-downside-protection',
      'https://docs.summer.fi/general/maximize-earnings-on-your-crypto-assets',
    ],
  },
  LEGACY_APP: 'https://legacy.summer.fi',
  AJNA: {
    HOME: 'https://www.ajna.finance/',
    AUDITS: 'https://github.com/ajna-finance/audits',
    OLD: 'https://old-ajna.summer.fi',
  },
  WORKABLE: 'https://summerfi.workable.com/',
  TWITTER: 'https://twitter.com/summerfinance_',
  DISCORD: 'https://discord.gg/summerfi',
  GITHUB: 'https://github.com/OasisDEX/oasis-borrow',
  BUG_BOUNTY: 'https://immunefi.com/bounty/summerfi',
  ETHERSCAN: 'https://etherscan.io',
  DUNE_ORG_STETHETH_PEG_HISTORY: 'https://dune.com/oasisapp/steth-eth-peg-history',
  METAMASK_12130_ISSUE: 'https://github.com/MetaMask/metamask-extension/issues/12130',
  ETHEREUM_ORG_MERKLING: 'https://blog.ethereum.org/2015/11/15/merkling-in-ethereum',
  WONDERWALL: 'https://www.youtube.com/embed/6hzrDeceEKc',
  LIDO_FI_STETH_LIQUIDITY:
    'https://blog.lido.fi/providing-steth-liquidity-via-curve-to-receive-rewards',
  AAVE_SDAI_YIELD_DUNE: 'https://dune.com/Lucianken/aave-v3-sdai-yield-multiple',
  HOW_TO_SET_UP_AUTO_TAKE_PROFIT_VIDEO: 'https://youtu.be/ZqnvxeccJDQ?feature=shared',
}
