FROM node:18.18-alpine
EXPOSE 3000
ENV YARN_VERSION=4.0.1
COPY server/database /app/server/database
WORKDIR /app/server/database
RUN yarn install --immutable
WORKDIR /app
COPY .next/standalone /app/.next/standalone
COPY package.json yarn.lock next.config.js /app
COPY public /app/.next/standalone/public
COPY .next/static /app/.next/standalone/.next/static

CMD [ "yarn", "start:prod" ]
