FROM node:16.13.2

EXPOSE 3000

RUN apt update && apt-get install -y libudev-dev && apt-get install libusb-1.0-0

COPY package.json /usr/src/app/package.json
COPY yarn.lock /usr/src/app/yarn.lock
COPY .next/ /usr/src/app/.next
COPY public/ /usr/src/app/public
COPY dist/ /usr/src/app/dist
COPY server/database/migrations/ /usr/src/app/server/database/migrations

WORKDIR /usr/src/app

ARG COMMIT_SHA
ARG API_HOST
ARG MIXPANEL_ENV
ARG MIXPANEL_KEY
ARG ADROLL_ADV_ID
ARG ADROLL_PIX_ID
ARG MAINNET_CACHE_URL
ARG SHOW_BUILD_INFO
ARG ETHERSCAN_API_KEY
ARG BLOCKNATIVE_API_KEY
ARG INFURA_PROJECT_ID
ARG NODE_ENV
ARG NEXT_PUBLIC_SENTRY_ENV
ARG SENTRY_AUTH_TOKEN

ENV COMMIT_SHA=$COMMIT_SHA \
    API_HOST=$API_HOST \
    MIXPANEL_ENV=$MIXPANEL_ENV \
    MIXPANEL_KEY=$MIXPANEL_KEY \
    ADROLL_ADV_ID=$ADROLL_ADV_ID \
    ADROLL_PIX_ID=$ADROLL_PIX_ID \
    MAINNET_CACHE_URL=$MAINNET_CACHE_URL \
    ETHERSCAN_API_KEY=$ETHERSCAN_API_KEY \
    BLOCKNATIVE_API_KEY=$BLOCKNATIVE_API_KEY \
    INFURA_PROJECT_ID=$INFURA_PROJECT_ID \
    USE_TERMS_OF_SERVICE=1 \
    SHOW_BUILD_INFO=$SHOW_BUILD_INFO \
    NODE_ENV=$NODE_ENV \
    SENTRY_RELEASE=$COMMIT_SHA \
    NEXT_PUBLIC_SENTRY_ENV=$NEXT_PUBLIC_SENTRY_ENV \
    SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN \
    NODE_OPTIONS=--max-old-space-size=4096

CMD [ "npm", "run", "start:prod" ]
