FROM node:20.18.0-alpine
EXPOSE 3000
COPY server/database /app/server/database
WORKDIR /app/server/database
RUN npm install --ignore-scripts
WORKDIR /app
COPY .next/standalone /app/.next/standalone
COPY package.json yarn.lock next.config.js /app
COPY public /app/.next/standalone/public
COPY .next/static /app/.next/standalone/.next/static

CMD [ "yarn", "start:prod" ]
