describe('autoTakeProfitFormChangeReducer', () => {
  it('should handle publish of close-type', () => {})
  it('should handle publish of execution-price', () => {})
  it('should handle publish of current-form', () => {})
  it('should handle publish of form-defaults', () => {})
  it('should handle publish of reset', () => {})
  it('should handle publish of is-editing', () => {})
  it('should handle publish of tx-details', () => {})
  it('should handle invalid action type', () => {})
})
