export const TOKENS_WITH_STAKING_REWARDS = ['APXETH', 'CBETH', 'OSETH', 'RETH', 'STYETH', 'WSTETH']
export const TOKENS_WITH_RESTAKING = ['EZETH', 'WEETH']
export const TOKENS_STABLE_GROUPS = ['DAI', 'FRAX', 'LUSD', 'SUSDE', 'USDC', 'USDT']
