export const automationBotAbi = [
  {
    inputs: [
      { internalType: 'contract IServiceRegistry', name: '_serviceRegistry', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes', name: 'triggerData', type: 'bytes' },
      { indexed: false, internalType: 'address', name: 'approvedEntity', type: 'address' },
    ],
    name: 'ApprovalGranted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'bytes', name: 'triggerData', type: 'bytes' },
      { indexed: false, internalType: 'address', name: 'approvedEntity', type: 'address' },
    ],
    name: 'ApprovalRemoved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'triggerId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'commandAddress', type: 'address' },
      { indexed: false, internalType: 'bool', name: 'continuous', type: 'bool' },
      { indexed: false, internalType: 'uint256', name: 'triggerType', type: 'uint256' },
      { indexed: false, internalType: 'bytes', name: 'triggerData', type: 'bytes' },
    ],
    name: 'TriggerAdded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'triggerId', type: 'uint256' },
      { indexed: false, internalType: 'bytes', name: 'executionData', type: 'bytes' },
    ],
    name: 'TriggerExecuted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'groupId', type: 'uint256' },
      { indexed: true, internalType: 'uint16', name: 'groupType', type: 'uint16' },
      { indexed: false, internalType: 'uint256[]', name: 'triggerIds', type: 'uint256[]' },
    ],
    name: 'TriggerGroupAdded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'uint256', name: 'triggerId', type: 'uint256' }],
    name: 'TriggerRemoved',
    type: 'event',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'activeTriggers',
    outputs: [
      { internalType: 'bytes32', name: 'triggerHash', type: 'bytes32' },
      { internalType: 'address', name: 'commandAddress', type: 'address' },
      { internalType: 'bool', name: 'continuous', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'triggerType', type: 'uint256' },
      { internalType: 'bool', name: 'continuous', type: 'bool' },
      { internalType: 'uint256', name: 'replacedTriggerId', type: 'uint256' },
      { internalType: 'bytes', name: 'triggerData', type: 'bytes' },
      { internalType: 'bytes', name: 'replacedTriggerData', type: 'bytes' },
    ],
    name: 'addRecord',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint16', name: 'groupType', type: 'uint16' },
      { internalType: 'bool[]', name: 'continuous', type: 'bool[]' },
      { internalType: 'uint256[]', name: 'replacedTriggerId', type: 'uint256[]' },
      { internalType: 'bytes[]', name: 'triggerData', type: 'bytes[]' },
      { internalType: 'bytes[]', name: 'replacedTriggerData', type: 'bytes[]' },
      { internalType: 'uint256[]', name: 'triggerTypes', type: 'uint256[]' },
    ],
    name: 'addTriggers',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'automationBot',
    outputs: [{ internalType: 'contract AutomationBot', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'clearLock', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [
      { internalType: 'uint16', name: 'triggerGroupType', type: 'uint16' },
      { internalType: 'uint256[]', name: 'triggerIds', type: 'uint256[]' },
    ],
    name: 'emitGroupDetails',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes', name: 'executionData', type: 'bytes' },
      { internalType: 'bytes', name: 'triggerData', type: 'bytes' },
      { internalType: 'address', name: 'commandAddress', type: 'address' },
      { internalType: 'uint256', name: 'triggerId', type: 'uint256' },
      { internalType: 'uint256', name: 'coverageAmount', type: 'uint256' },
      { internalType: 'address', name: 'coverageToken', type: 'address' },
    ],
    name: 'execute',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'commandAddress', type: 'address' },
      { internalType: 'bool', name: 'isExecute', type: 'bool' },
    ],
    name: 'getAdapterAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'triggerType', type: 'uint256' }],
    name: 'getCommandAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
    name: 'getTriggerRecord',
    outputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'triggerHash', type: 'bytes32' },
          { internalType: 'address', name: 'commandAddress', type: 'address' },
          { internalType: 'bool', name: 'continuous', type: 'bool' },
        ],
        internalType: 'struct AutomationBot.TriggerRecord',
        name: 'rec',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint16', name: 'groupType', type: 'uint16' }],
    name: 'getValidatorAddress',
    outputs: [{ internalType: 'contract IValidator', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes', name: 'triggerData', type: 'bytes' },
      { internalType: 'uint256', name: 'triggerId', type: 'uint256' },
    ],
    name: 'removeRecord',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256[]', name: 'triggerIds', type: 'uint256[]' },
      { internalType: 'bytes[]', name: 'triggerData', type: 'bytes[]' },
      { internalType: 'bool', name: 'removeAllowance', type: 'bool' },
    ],
    name: 'removeTriggers',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'serviceRegistry',
    outputs: [{ internalType: 'contract IServiceRegistry', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'triggersCounter',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'triggersGroupCounter',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const
