import { zero } from 'helpers/zero'

// this is basic history interface that we are getting
// from history subgraphs, to be used across all protocols
// when will be migrated to omni-kit
export const unifiedDefaultHistoryItem = {
  depositAmount: zero,
  withdrawAmount: zero,
  blockNumber: zero,
  collateralAddress: '',
  collateralAfter: zero,
  collateralBefore: zero,
  collateralDelta: zero,
  collateralOraclePrice: zero,
  collateralToken: '',
  collateralTokenPriceUSD: zero,
  debtAddress: '',
  debtAfter: zero,
  debtBefore: zero,
  debtDelta: zero,
  debtOraclePrice: zero,
  debtToken: '',
  debtTokenPriceUSD: zero,
  depositedUSD: zero,
  ethPrice: zero,
  gasFeeUSD: zero,
  gasPrice: zero,
  gasUsed: zero,
  id: '',
  kind: '',
  liquidationPriceAfter: zero,
  liquidationPriceBefore: zero,
  ltvAfter: zero,
  ltvBefore: zero,
  marketPrice: zero,
  multipleAfter: zero,
  multipleBefore: zero,
  netValueAfter: zero,
  netValueBefore: zero,
  oasisFee: zero,
  oasisFeeToken: '',
  oasisFeeUSD: zero,
  quoteTokensAfter: zero,
  quoteTokensBefore: zero,
  quoteTokensDelta: zero,
  isOpen: false,
  swapFromAmount: zero,
  swapFromToken: '',
  swapToAmount: zero,
  swapToToken: '',
  timestamp: 0,
  totalFee: zero,
  totalFeeInQuoteToken: zero,
  txHash: '',
  withdrawnUSD: zero,
}
