import { MainNetworkNames } from 'blockchain/networks'
import { TokenConfig } from 'blockchain/tokensMetadata'
import { LendingProtocol } from 'lendingProtocols'

export const ajnaTokensMetadata: TokenConfig[] = [
  {
    symbol: 'GHO',
    precision: 18,
    digits: 5,
    name: 'GHO',
    icon: 'gho_circle_color',
    iconCircle: 'gho_circle_color',
    color: '#C9B9EE',
    background: '',
    bannerIcon: '',
    bannerGif: '',
    coinbaseTicker: 'gho',
    coinGeckoTicker: 'gho',
    coinpaprikaTicker: 'gho-gho',
    tags: [],
    protocol: LendingProtocol.Ajna,
    chain: MainNetworkNames.ethereumMainnet,
  },
  {
    symbol: 'SDAI',
    precision: 18,
    digits: 4,
    name: 'Savings Dai',
    icon: 'gho_circle_color',
    iconCircle: 'dai_circle_color',
    color: '#54ac3c',
    background: '',
    bannerIcon: '',
    bannerGif: '',
    oracleTicker: 'sdai',
    tags: [],
    protocol: LendingProtocol.Ajna,
    chain: MainNetworkNames.ethereumMainnet,
  },
  {
    symbol: 'WLD',
    precision: 18,
    digits: 5,
    name: 'Worldcoin',
    icon: 'wld_circle_color',
    iconCircle: 'wld_circle_color',
    color: '#1e1e1c',
    background: '',
    bannerIcon: '',
    bannerGif: '',
    coinbaseTicker: 'worldcoin-org',
    coinGeckoTicker: 'worldcoin-wld',
    coinpaprikaTicker: 'wld-worldcoi',
    tags: [],
    protocol: LendingProtocol.Ajna,
    chain: MainNetworkNames.ethereumMainnet,
  },
]
