import { MainNetworkNames } from 'blockchain/networks'
import { TokenConfig } from 'blockchain/tokensMetadata'
import { LendingProtocol } from 'lendingProtocols'

export const ajnaTokensMetadata: TokenConfig[] = [
  {
    symbol: 'GHO',
    precision: 18,
    digits: 5,
    name: 'GHO',
    icon: 'gho_circle_color',
    iconCircle: 'gho_circle_color',
    color: '#C9B9EE',
    background: '',
    bannerIcon: '',
    bannerGif: '',
    coinGeckoTicker: 'gho',
    coinpaprikaTicker: 'gho-gho',
    tags: [],
    protocol: LendingProtocol.Ajna,
    chain: MainNetworkNames.ethereumMainnet,
  },
  {
    symbol: 'SDAI',
    precision: 18,
    digits: 4,
    name: 'Savings Dai',
    icon: 'gho_circle_color',
    iconCircle: 'sdai_circle_color',
    color: '#54ac3c',
    background: '',
    bannerIcon: '',
    bannerGif: '',
    oracleTicker: 'sdai',
    tags: [],
    protocol: LendingProtocol.Ajna,
    chain: MainNetworkNames.ethereumMainnet,
  },
  {
    symbol: 'TBTC',
    precision: 18,
    digits: 5,
    name: 'Threshold Bitcoin',
    icon: 'tbtc_circle_color',
    iconCircle: 'tbtc_circle_color',
    color: '#000000',
    background: '',
    bannerIcon: '',
    bannerGif: '',
    coinbaseTicker: 'btc-usd',
    coinGeckoTicker: 'bitcoin',
    coinpaprikaTicker: 'btc-bitcoin',
    rootToken: 'BTC',
    tags: [],
    protocol: LendingProtocol.Ajna,
    chain: MainNetworkNames.ethereumMainnet,
  },
  {
    symbol: 'WLD',
    precision: 18,
    digits: 5,
    name: 'Worldcoin',
    icon: 'wld_circle_color',
    iconCircle: 'wld_circle_color',
    color: '#1e1e1c',
    background: '',
    bannerIcon: '',
    bannerGif: '',
    coinGeckoTicker: 'worldcoin-wld',
    coinpaprikaTicker: 'wld-worldcoin',
    tags: [],
    protocol: LendingProtocol.Ajna,
    chain: MainNetworkNames.ethereumMainnet,
  },
  {
    symbol: 'YIELDETH',
    precision: 18,
    digits: 5,
    name: 'Real Yield ETH',
    icon: 'yieldeth_circle_color',
    iconCircle: 'yieldeth_circle_color',
    color: '#17438C',
    background: '',
    bannerIcon: '',
    bannerGif: '',
    rootToken: 'ETH',
    tags: [],
    protocol: LendingProtocol.Ajna,
    chain: MainNetworkNames.ethereumMainnet,
  },
  {
    symbol: 'YIELDBTC',
    precision: 18,
    digits: 5,
    name: 'Real Yield BTC',
    icon: 'yieldbtc_circle_color',
    iconCircle: 'yieldbtc_circle_color',
    color: '#17438C',
    background: '',
    bannerIcon: '',
    bannerGif: '',
    rootToken: 'BTC',
    tags: [],
    protocol: LendingProtocol.Ajna,
    chain: MainNetworkNames.ethereumMainnet,
  },
]
