import { staticFilesRuntimeUrl } from 'helpers/staticPaths'
import { keyBy } from 'lodash'
import type { ElementOf } from 'ts-essentials'

export interface TokenConfig {
  symbol: string
  precision: number
  digits: number
  maxSell: string
  name: string
  icon: string
  iconCircle: string
  iconColor: string
  ticker: string
  tags: CoinTag[]
  color: string
  bannerIcon: string
  bannerIconPng: string
}

export const COIN_TAGS = ['stablecoin', 'lp-token'] as const
export type CoinTag = ElementOf<typeof COIN_TAGS>

export const tokens = [
  {
    symbol: 'ETH',
    precision: 18,
    digits: 5,
    maxSell: '10000000',
    name: 'Ether',
    icon: 'ether',
    iconCircle: 'ether_circle_color',
    iconColor: 'ether_color',
    ticker: 'eth-ethereum',
    coinbaseTicker: 'eth-usdc',
    color: '#667FE3',
    background: 'linear-gradient(340.03deg, #D0AFF0 0%, #1837DD 99.08%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/eth.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/ETH.png'),
    tags: [],
    description: {
      en:
        'ETH is the transactional token that facilitates operations on the Ethereum network, being a form of payment for network participants to execute their requested operations on it. We can think about it as the "fuel" of the network. Users may exchange other cryptocurrencies for ether tokens, but ether tokens cannot be substituted with other cryptocurrencies to provide computing power for Ethereum transactions',
    },
    link: 'https://ethereum.org/en/eth/',
  },
  {
    symbol: 'BAT',
    precision: 18,
    digits: 5,
    name: 'Basic Attention Token',
    icon: 'bat',
    iconCircle: 'bat_circle_color',
    iconColor: 'bat_color',
    color: '#ff4625',
    background: 'linear-gradient(147.66deg, #F48702 0%, #FCBD71 88.24%, #FC9371 110.25%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/bat.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/BAT.png'),
    tags: [],
    description: {
      en: `The BAT that powers Brave Software's blockchain-based digital advertising platform. The browser blocks trackers, malware and invasive cookies.The token is deployed with smart contracts issued directly from the advertiser. Users get rewarded for their “attention” by watching ads in an anonymous, blockchain based environment. Creators also receive rewards and revenue for content creation.`,
    },
    link: 'https://basicattentiontoken.org/#ad-network',
  },
  {
    symbol: 'WBTC',
    precision: 8,
    digits: 5,
    digitsInstant: 3,
    safeCollRatio: 1.5,
    maxSell: '1000000000000000',
    name: 'Wrapped Bitcoin',
    icon: 'wbtc',
    iconCircle: 'wbtc_circle_color',
    iconColor: 'wbtc_circle_color',
    ticker: 'wbtc-wrapped-bitcoin',
    color: '#f09242',
    background: 'linear-gradient(147.66deg, #F48702 0%, #FCBD71 88.24%, #FC9371 110.25%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/wbtc.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/WBTC.png'),
    tags: [],
    description: {
      en:
        'Wrapped Bitcoin delivers the power of Bitcoin with the flexibility of an ERC20 token. It is the first ERC20 token backed 1:1 with Bitcoin. It is completely transparent, 100% verifiable and community led. WBTC bringd Bitcoin’s liquidity to DEXs and makes it possible to use Bitcoin for token trades.',
    },
    link: 'https://wbtc.network/',
  },
  {
    symbol: 'RENBTC',
    precision: 8,
    digits: 5,
    digitsInstant: 3,
    safeCollRatio: 1.5,
    maxSell: '1000000000000000',
    name: 'renBTC',
    icon: 'renbtc',
    iconCircle: 'renbtc_circle_color',
    iconColor: 'renbtc_circle_color',
    ticker: 'renbtc-renbtc',
    color: '#838489',
    background: 'linear-gradient(156.14deg, #222121 12.76%, #8E8E8E 93.58%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/renbtc.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/renBTC.png'),
    tags: [],
    description: {
      en:
        'RenBTC is an ERC-20 token built on the Ethereum network, pegged to Bitcoin and minted on the Ren platform, which is an open protocol helping to bring assets from other blockchains to Ethereum decentralized applications (DApps). To mint it, the users send their BTC to RenVM, which then secures the asset and mints an equivalent number of renBTC.',
    },
    link: 'https://renproject.io/',
  },
  {
    symbol: 'TUSD',
    precision: 18,
    digits: 2,
    name: 'Trust token',
    icon: 'tusd',
    iconCircle: 'tusd_circle_color',
    iconColor: 'tusd_color',
    color: '#195aff',
    background: 'linear-gradient(141.5deg, #164BE1 14.6%, #517BE7 52.11%, #8DA6EC 89.62%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/tusd.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/TUSD.png'),
    tags: ['stablecoin'],
    description: {
      en:
        'TUSD is a 1:1 USD-backed centralized stablecoin, it is an ERC-20 token, part of the TrustToken asset tokenization platform.',
    },
    link: 'https://www.trusttoken.com/',
  },
  {
    symbol: 'KNC',
    precision: 18,
    digits: 5,
    name: 'Kyber Network',
    icon: 'kyber',
    iconCircle: 'kyber_circle_color',
    iconColor: 'kyber_color',
    color: '#30cb9e',
    background: 'linear-gradient(141.71deg, #00AF87 17.09%, #1ACCA4 81.72%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/knc.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/KNC.png'),
    tags: [],
    description: {
      en:
        'KNC is an Ethereum token used for paying fees on the Kyber Network, a blockchain-based liquidity hub that connects liquidity from a wide range of sources to power instant and secure crypto exchange in any decentralized application.',
    },
    link: 'https://kyber.network/',
  },
  {
    symbol: 'MANA',
    precision: 18,
    digits: 5,
    name: 'Decentraland',
    icon: 'mana',
    iconCircle: 'mana_circle_color',
    iconColor: 'mana_color',
    color: '#f05',
    background: 'linear-gradient(318.4deg, #FFBC5B 3.1%, #FF2D55 100%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/mana.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/MANA.png'),
    tags: [],
    description: {
      en:
        'MANA is the ERC-20 token built for Decentraland, a virtual reality platform powered by the ethereum blockchain. It is primarily used to buy goods, services and LAND (an NFT token) within Decentraland.',
    },
    link: 'https://decentraland.org/',
  },
  {
    symbol: 'PAXUSD',
    precision: 18,
    digits: 2,
    name: 'Paxos Standard',
    icon: 'pax',
    iconCircle: 'pax_circle_color',
    iconColor: 'pax_color',
    color: '#005121',
    background: 'linear-gradient(143.13deg, #0B9F74 12.24%, #64DFBB 85.9%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/pax.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/PAX.png'),
    tags: ['stablecoin'],
    description: {
      en:
        'Pax Dollar is a 1:1 USD-backed centralized stablecoin, it is an ERC-20 token. The correspondent dollars are held in Paxos-owned US bank accounts. Paxos is a regulated blockchain infrastructure platform, building a new, open financial system.',
    },
    link: 'https://www.paxos.com/',
  },
  {
    symbol: 'USDT',
    precision: 6,
    digits: 2,
    name: 'Tether',
    icon: 'usdt',
    iconCircle: 'usdt_circle_color',
    iconColor: 'usdt_color',
    color: '259c77',
    background: 'linear-gradient(141.71deg, #00AF87 17.09%, #1ACCA4 81.72%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/usdt.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/USDT.png'),
    tags: ['stablecoin'],
    description: {
      en:
        'Tether is a centralized stablecoin, backed 100% by fiat currency. USDT is equal to one unit of the coin it is anchored to, the US Dollar. Tether allows users to use fiat-backed tokens on blockchains and bypass the price volatility of other cryptocurrencies.',
    },
    link: 'https://tether.to/',
  },
  {
    symbol: 'COMP',
    precision: 18,
    digits: 5,
    name: 'Compound',
    icon: 'compound',
    iconCircle: 'compound_circle_color',
    iconColor: 'compound_color',
    color: '#00D395',
    background:
      'linear-gradient(180deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.05) 100%), linear-gradient(290.37deg, #54D8B1 0%, #2DAA7D 96.14%), linear-gradient(290.37deg, #4BCFA8 0%, #139D8D 96.14%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/comp.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/COMP.png'),
    tags: [],
    description: {
      en:
        'Compound (COMP) is the governance token of Compound protocol. Compound is an algorithmic, autonomous interest rate protocol built for developers, to unlock a universe of open financial applications.',
    },
    link: 'https://compound.finance/',
  },
  {
    symbol: 'LRC',
    precision: 18,
    digits: 5,
    name: 'Loopring',
    icon: 'lrc',
    iconCircle: 'lrc_circle_color',
    iconColor: 'lrc_color',
    color: '#1c60ff',
    background: 'linear-gradient(143.13deg, #3758FD 17.87%, #A1ADEA 91.53%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/lrc.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/LRC.png'),
    tags: [],
    description: {
      en:
        'Loopring is an Ethereum token that describes itself as “an open-sourced, audited, and non-custodial exchange protocol.” It aims to allow anyone to build non-custodial, order book-based exchanges on Ethereum by leveraging zero-knowledge proofs.',
    },
    link: 'https://loopring.org/',
  },
  {
    symbol: 'LINK',
    precision: 18,
    digits: 5,
    name: 'Chainlink',
    icon: 'chainlink',
    iconCircle: 'chainlink_circle_color',
    iconColor: 'chainlink_color',
    color: '#375bd2',
    background: 'linear-gradient(142.24deg, #164BE1 0.76%, #678FFD 45.26%, #A87FFD 89.76%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/link.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/LINK.png'),
    tags: [],
    description: {
      en:
        'LINK is an ERC-20 token used in the Chainlink network to compensate Chainlink Node operators for the retrieval of data from the external data sources. Chainlink is a blockchain-based cryptocurrency network that provides a link between real world data and smart contracts.',
    },
    link: 'https://chain.link/',
  },
  {
    symbol: 'GUSD',
    precision: 2,
    digits: 2,
    name: 'Gemini dollar',
    icon: 'gemini',
    iconCircle: 'gemini_circle_color',
    iconColor: 'gemini_color',
    color: '#25ddfb',
    background: 'linear-gradient(144.58deg, #00B4CC 15.16%, #93E9F4 89.41%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/gusd.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/GUSD.png'),
    tags: ['stablecoin'],
    description: {
      en:
        'The Gemini Dollar is a 1:1 USD-backed centralized stablecoin, an ERC20 token built atop the Ethereum network whose purpose is to bridge the divide between the traditional finance sector and the crypto industry. Gemini is a regulated cryptocurrency exchange, wallet, and custodian that makes it simple and secure to buy bitcoin, ether, and other cryptocurrencies.',
    },
    link: 'https://www.gemini.com/eu',
  },
  {
    symbol: 'ZRX',
    precision: 18,
    digits: 5,
    name: '0x',
    icon: 'zerox',
    iconCircle: 'zerox_circle_color',
    iconColor: 'zerox_color',
    color: '#000',
    background: 'linear-gradient(156.14deg, #222121 12.76%, #8E8E8E 93.58%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/zerox.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/ZRX.png'),
    tags: [],
    description: {
      en:
        'ZRX is the native governance and staking token for 0x, the open protocol that enables the peer-to-peer exchange of assets on the Ethereum blockchain. The peer-to-peer decentralised exchange is mainly used to pay trading fees and governance as it doesn’t interact with fiat currency.',
    },
    link: 'https://0x.org/',
  },
  {
    symbol: 'USDC',
    precision: 6,
    digits: 6,
    digitsInstant: 2,
    maxSell: '1000000000000000',
    name: 'USD Coin',
    icon: 'usdc',
    iconCircle: 'usdc_circle_color',
    iconColor: 'usdc_circle_color',
    ticker: 'usdc-usd-coin',
    color: '#2775ca',
    background: 'linear-gradient(134.29deg, #0666CE 1.99%, #61A9F8 41.43%, #33CEE3 97.83%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/usdc.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/USDC.png'),
    tags: ['stablecoin'],
    description: {
      en:
        'USDC is a 1:1 USD-backed centralized stablecoin, fully regulated. USDC is natively supported on multiple layer 1 blockchains including Ethereum as an ERC-20 token, Algorand as an ASA token, Solana as a SPL token, TRON as an TRC-20 token, and Stellar as a native asset. It is operated by Circle.',
    },
    link: 'https://www.circle.com/en/about-circle',
  },
  {
    symbol: 'BAL',
    precision: 18,
    digits: 5,
    digitsInstant: 2,
    name: 'Balancer',
    icon: 'usdc',
    iconCircle: 'bal_circle',
    iconColor: 'bal_circle_color',
    color: '#000',
    background: 'linear-gradient(156.14deg, #222121 12.76%, #8E8E8E 93.58%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/bal.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/BAL.png'),
    tags: [],
    description: {
      en:
        'Balancer (BAL) is an Ethereum token that powers the Balancer protocol, an automated market maker that lets anyone create or add liquidity to trading pools while earning customizable trading fees. BAL is the governance token of the protocol.',
    },
    link: 'https://balancer.fi/',
  },
  {
    symbol: 'YFI',
    precision: 18,
    digits: 5,
    digitsInstant: 2,
    name: 'Yearn',
    icon: 'usdc',
    iconCircle: 'yfi_circle_color',
    iconColor: 'yfi_circle_color',
    color: '#0657f9',
    background: 'linear-gradient(145.44deg, #0060CD 17.44%, #6AADFA 91.11%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/yfi.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/YFI.png'),
    tags: [],
    description: {
      en:
        'Yearn.finance (YFI) is the governance token of the Yearn.finance platform. The platform is a yield optimizer that moves funds around the decentralized finance ecosystem in an effort to generate a high return.',
    },
    link: 'https://yearn.finance/',
  },
  {
    symbol: 'UNI',
    precision: 18,
    digits: 5,
    digitsInstant: 2,
    name: 'Uniswap',
    icon: 'uni_circle_color',
    iconCircle: 'uni_circle_color',
    iconColor: 'uni_circle_color',
    color: '#ff077d',
    background:
      'linear-gradient(180deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.05) 100%), linear-gradient(99.1deg, #FA46A7 0%, #FF599F 95.28%), linear-gradient(99.1deg, #FF077D 0%, #FF5B79 95.28%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/uni.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/UNI.png'),
    tags: [],
    description: {
      en:
        'UNI is the governance token of Uniswap Protocol, which is governed by a decentralized community of UNI token holders and their delegates who propose and vote on upgrades to the protocol. Uniswap is a crypto trading protocol for swapping ERC20 tokens.',
    },
    link: 'https://uniswap.org/',
  },
  {
    symbol: 'AAVE',
    precision: 18,
    digits: 5,
    digitsInstant: 2,
    name: 'Aave',
    icon: 'aave_circle_color',
    iconCircle: 'aave_circle_color',
    iconColor: 'aave_circle_color',
    color: '#ff077d',
    background: 'linear-gradient(286.73deg, #B6509E 2.03%, #2EBAC6 100%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/aave.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/AAVE.png'),
    tags: [],
    description: {
      en:
        'Aave is the governance token of Aave protocol. Aave is a decentralized finance protocol that lets people lend and borrow cryptocurrency without having to go through a centralized intermediary. When they lend, they earn interest; when they borrow, they pay interest.',
    },
    link: 'https://aave.com/',
  },
  {
    symbol: 'UNIV2USDCETH',
    precision: 18,
    digits: 5,
    digitsInstant: 2,
    name: 'UNIV2USDCETH',
    icon: 'uni_circle_color',
    iconCircle: 'uni_circle_color',
    iconColor: 'uni_circle_color',
    color: '#ff077d',
    background:
      'linear-gradient(99.1deg, #FFA09A 0%, #FF748D 43.67%, #EB61B4 95.28%), linear-gradient(99.1deg, #FF077D 0%, #FF5B79 95.28%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/uni.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/UNI.png'),
    tags: ['lp-token'],
  },
  {
    symbol: 'UNIV2DAIUSDC',
    precision: 18,
    digits: 5,
    digitsInstant: 2,
    name: 'UNIV2DAIUSDC',
    icon: 'uni_circle_color',
    iconCircle: 'uni_circle_color',
    iconColor: 'uni_circle_color',
    color: '#ff077d',
    background:
      'linear-gradient(99.1deg, #FFA09A 0%, #FF748D 43.67%, #EB61B4 95.28%), linear-gradient(99.1deg, #FF077D 0%, #FF5B79 95.28%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/uni.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/UNI.png'),
    tags: ['lp-token'],
  },
  {
    symbol: 'UNIV2WBTCETH',
    precision: 18,
    digits: 5,
    digitsInstant: 2,
    name: 'UNIV2WBTCETH',
    icon: 'uni_circle_color',
    iconCircle: 'uni_circle_color',
    iconColor: 'uni_circle_color',
    color: '#ff077d',
    background:
      'linear-gradient(99.1deg, #FFA09A 0%, #FF748D 43.67%, #EB61B4 95.28%), linear-gradient(99.1deg, #FF077D 0%, #FF5B79 95.28%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/uni.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/UNI.png'),
    tags: ['lp-token'],
  },
  {
    symbol: 'UNIV2DAIETH',
    precision: 18,
    digits: 5,
    digitsInstant: 2,
    name: 'UNIV2DAIETH',
    icon: 'uni_circle_color',
    iconCircle: 'uni_circle_color',
    iconColor: 'uni_circle_color',
    color: '#ff077d',
    background:
      'linear-gradient(99.1deg, #FFA09A 0%, #FF748D 43.67%, #EB61B4 95.28%), linear-gradient(99.1deg, #FF077D 0%, #FF5B79 95.28%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/uni.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/UNI.png'),
    tags: ['lp-token'],
  },
  {
    symbol: 'UNIV2ETHUSDT',
    precision: 18,
    digits: 5,
    digitsInstant: 2,
    name: 'UNIV2ETHUSDT',
    icon: 'uni_circle_color',
    iconCircle: 'uni_circle_color',
    iconColor: 'uni_circle_color',
    color: '#ff077d',
    background:
      'linear-gradient(99.1deg, #FFA09A 0%, #FF748D 43.67%, #EB61B4 95.28%), linear-gradient(99.1deg, #FF077D 0%, #FF5B79 95.28%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/uni.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/UNI.png'),
    tags: ['lp-token'],
  },
  {
    symbol: 'UNIV2UNIETH',
    precision: 18,
    digits: 5,
    digitsInstant: 2,
    name: 'UNIV2UNIETH',
    icon: 'uni_circle_color',
    iconCircle: 'uni_circle_color',
    iconColor: 'uni_circle_color',
    color: '#ff077d',
    background:
      'linear-gradient(99.1deg, #FFA09A 0%, #FF748D 43.67%, #EB61B4 95.28%), linear-gradient(99.1deg, #FF077D 0%, #FF5B79 95.28%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/uni.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/UNI.png'),
    tags: ['lp-token'],
  },
  {
    symbol: 'UNIV2LINKETH',
    precision: 18,
    digits: 5,
    digitsInstant: 2,
    name: 'UNIV2LINKETH',
    icon: 'uni_circle_color',
    iconCircle: 'uni_circle_color',
    iconColor: 'uni_circle_color',
    color: '#ff077d',
    background:
      'linear-gradient(99.1deg, #FFA09A 0%, #FF748D 43.67%, #EB61B4 95.28%), linear-gradient(99.1deg, #FF077D 0%, #FF5B79 95.28%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/uni.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/UNI.png'),
    tags: ['lp-token'],
  },
  {
    symbol: 'UNIV2WBTCDAI',
    precision: 18,
    digits: 5,
    digitsInstant: 2,
    name: 'UNIV2WBTCDAI',
    icon: 'uni_circle_color',
    iconCircle: 'uni_circle_color',
    iconColor: 'uni_circle_color',
    color: '#ff077d',
    background:
      'linear-gradient(99.1deg, #FFA09A 0%, #FF748D 43.67%, #EB61B4 95.28%), linear-gradient(99.1deg, #FF077D 0%, #FF5B79 95.28%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/uni.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/UNI.png'),
    tags: ['lp-token'],
  },
  {
    symbol: 'UNIV2AAVEETH',
    precision: 18,
    digits: 5,
    digitsInstant: 2,
    name: 'UNIV2AAVEETH',
    icon: 'uni_circle_color',
    iconCircle: 'uni_circle_color',
    iconColor: 'uni_circle_color',
    color: '#ff077d',
    background:
      'linear-gradient(99.1deg, #FFA09A 0%, #FF748D 43.67%, #EB61B4 95.28%), linear-gradient(99.1deg, #FF077D 0%, #FF5B79 95.28%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/uni.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/UNI.png'),
    tags: ['lp-token'],
  },
  {
    symbol: 'UNIV2DAIUSDT',
    precision: 18,
    digits: 5,
    digitsInstant: 2,
    name: 'UNIV2DAIUSDT',
    icon: 'uni_circle_color',
    iconCircle: 'uni_circle_color',
    iconColor: 'uni_circle_color',
    color: '#ff077d',
    background:
      'linear-gradient(99.1deg, #FFA09A 0%, #FF748D 43.67%, #EB61B4 95.28%), linear-gradient(99.1deg, #FF077D 0%, #FF5B79 95.28%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/uni.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/UNI.png'),
    tags: ['lp-token'],
  },
  {
    symbol: 'UNI LP Tokens',
    precision: 18,
    digits: 5,
    digitsInstant: 2,
    name: 'UNI LP Tokens',
    icon: 'uni_circle_color',
    iconCircle: 'uni_circle_color',
    iconColor: 'uni_circle_color',
    color: '#ff077d',
    background:
      'linear-gradient(99.1deg, #FFA09A 0%, #FF748D 43.67%, #EB61B4 95.28%), linear-gradient(99.1deg, #FF077D 0%, #FF5B79 95.28%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/uni.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/UNI.png'),
    tags: [],
    description: {
      en:
        'When tokens are deposited into a crypto liquidity pool, the platform automatically generates a new token that represents the share the depositor owns of that pool. This is called a liquidity provider (LP) token, and it can be used for a multitude of functions both within its native platform and other decentralized finance (DeFi) apps. This has the effect of multiplying the liquidity available in the DeFi ecosystem.',
    },
    link: 'https://uniswap.org/',
  },
  {
    symbol: 'GUNIV3DAIUSDC1',
    precision: 18,
    digits: 5,
    digitsInstant: 2,
    name: 'GUNIV3DAIUSDC1',
    icon: 'uni_circle_color',
    iconCircle: 'uni_circle_color',
    iconColor: 'uni_circle_color',
    color: '#ff077d',
    background:
      'linear-gradient(99.1deg, #FFA09A 0%, #FF748D 43.67%, #EB61B4 95.28%), linear-gradient(99.1deg, #FF077D 0%, #FF5B79 95.28%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/uni.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/UNI.png'),
    tags: ['lp-token'],
  },
  {
    symbol: 'MATIC',
    precision: 18,
    digits: 5,
    digitsInstant: 2,
    name: 'MATIC',
    icon: 'matic_circle_color',
    iconCircle: 'matic_circle_color',
    iconColor: 'matic_circle_color',
    color: '#ff077d',
    background: 'linear-gradient(106.31deg, #8246E4 0%, #DB45F3 100%)',
    bannerIcon: staticFilesRuntimeUrl('/static/img/banner_icons/matic.svg'),
    bannerIconPng: staticFilesRuntimeUrl('/static/img/banner_icons/MATIC.png'),
    tags: [],
    description: {
      en:
        'Polygon (MATIC) is an Ethereum token that powers the Polygon Network, a scaling solution for Ethereum. Polygon is a protocol and a framework for building and connecting Ethereum-compatible blockchain networks. Aggregating scalable solutions on Ethereum supporting a multi-chain Ethereum ecosystem.',
    },
    link: 'https://polygon.technology/',
  },
  // {
  //   symbol: 'WETH',
  //   precision: 18,
  //   digits: 5,
  //   maxSell: '10000000',
  //   name: 'Wrapped Ether',
  //   icon: AvatarSimple(ethSvg),
  //   // iconInverse: AvatarSimple(ethCircleSvg),
  //   iconCircle: AvatarSimple(ethCircleSvg),
  //   iconColor: AvatarSimple(ethCircleSvg),
  //   ticker: 'eth-ethereum',
  // },
  {
    symbol: 'DAI',
    precision: 18,
    digits: 4,
    maxSell: '10000000',
    name: 'Dai',
    icon: 'dai',
    iconCircle: 'dai_circle_color',
    iconColor: 'dai_color',
    ticker: 'dai-dai',
    coinbaseTicker: 'dai-usdc',
    color: '#fdc134',
    tags: ['stablecoin'],
  },
  // {

  // },
  // {
  //   symbol: 'CHAI',
  //   precision: 18,
  //   digits: 4,
  //   maxSell: '10000000',
  //   name: 'Maker',
  //   icon: AvatarSimple(mkrSvg),
  //   iconCircle: AvatarSimple(mkrSvg),
  //   iconColor: AvatarSimple(mkrSvg),
  //   ticker: '',
  // },
  // {
  //   symbol: 'MKR',
  //   precision: 18,
  //   digits: 4,
  //   maxSell: '10000000',
  //   name: 'Maker',
  //   icon: AvatarSimple(mkrSvg),
  //   iconCircle: AvatarSimple(mkrSvg),
  //   iconColor: AvatarSimple(mkrSvg),
  //   ticker: 'usdc-usd-coin',
  // },
]

// ticker comes from coinpaprika api https://api.coinpaprika.com/v1/tickers
const tokensBySymbol = keyBy(tokens, 'symbol')

export function getToken(tokenSymbol: string) {
  if (!tokensBySymbol[tokenSymbol]) {
    throw new Error(`No meta information for token: ${tokenSymbol}`)
  }
  return tokensBySymbol[tokenSymbol]
}

export const ALLOWED_MULTIPLY_TOKENS = tokens
  .filter(
    (token) => !(token.tags as CoinTag[]).some((tag) => tag === 'lp-token' || tag === 'stablecoin'),
  )
  .map((token) => token.symbol)
