import { keyBy } from 'lodash'

export interface TokenConfig {
  symbol: string
  precision: number
  digits: number
  maxSell: string
  name: string
  icon: string
  iconCircle: string
  iconColor: string
  ticker: string
}

const tokens = [
  {
    symbol: 'ETH',
    precision: 18,
    digits: 5,
    maxSell: '10000000',
    name: 'Ether',
    icon: 'ether',
    iconCircle: 'ether_circle_color',
    iconColor: 'ether_color',
    ticker: 'eth-ethereum',
    coinbaseTicker: 'eth-usdc',
    color: '#667FE3',
    background: 'linear-gradient(284.73deg, #9658D3 3.42%, #415FFF 97.28%)',
  },
  {
    symbol: 'BAT',
    precision: 18,
    // digits: ___________,
    // maxSell: ___________,
    name: 'Basic Attention Token',
    icon: 'bat',
    // iconCircle: ___________,
    // iconColor: ___________,
    // ticker: ___________,
    // coinbaseTicker: ___________,
  },
  {
    symbol: 'WBTC',
    precision: 8,
    digits: 5,
    digitsInstant: 3,
    safeCollRatio: 1.5,
    maxSell: '1000000000000000',
    name: 'Wrapped Bitcoin',
    icon: 'wbtc',
    iconCircle: 'wbtc',
    iconColor: 'wbtc_color',
    ticker: 'wbtc-wrapped-bitcoin',
  },
  {
    symbol: 'TUSD',
    precision: 18,
    // digits: ___________,
    // maxSell: ___________,
    name: 'Trust token',
    icon: 'tusd',
    // iconCircle: ___________,
    // iconColor: ___________,
    // ticker: ___________,
    // coinbaseTicker: ___________,
  },
  {
    symbol: 'KNC',
    precision: 18,
    // digits: ___________,
    // maxSell: ___________,
    name: 'Kyber Network',
    icon: 'kyber',
    // iconCircle: ___________,
    // iconColor: ___________,
    // ticker: ___________,
    // coinbaseTicker: ___________,
  },
  {
    symbol: 'MANA',
    precision: 18,
    // digits: ___________,
    // maxSell: ___________,
    name: 'Decentraland',
    icon: 'mana',
    // iconCircle: ___________,
    // iconColor: ___________,
    // ticker: ___________,
    // coinbaseTicker: ___________,
  },
  {
    symbol: 'PAXUSD',
    precision: 18,
    // digits: ___________,
    // maxSell: ___________,
    name: 'Paxos Standard',
    icon: 'pax',
    // iconCircle: ___________,
    // iconColor: ___________,
    // ticker: ___________,
    // coinbaseTicker: ___________,
  },
  {
    symbol: 'USDT',
    precision: 6,
    // digits: ___________,
    // maxSell: ___________,
    name: 'Tether',
    icon: 'usdt',
    // iconCircle: ___________,
    // iconColor: ___________,
    // ticker: ___________,
    // coinbaseTicker: ___________,
  },
  {
    symbol: 'COMP',
    precision: 18,
    // digits: ___________,
    // maxSell: ___________,
    name: 'Compound',
    icon: 'compound',
    color: '#00D395',
    background: 'linear-gradient(290.37deg, #4BCFA8 0%, #139D8D 96.14%)',
    // iconCircle: ___________,
    // iconColor: ___________,
    // ticker: ___________,
    // coinbaseTicker: ___________,
  },
  {
    symbol: 'LRC',
    precision: 18,
    // digits: ___________,
    // maxSell: ___________,
    name: 'Loopring',
    icon: 'lrc',
    // iconCircle: ___________,
    // iconColor: ___________,
    // ticker: ___________,
    // coinbaseTicker: ___________,
  },
  {
    symbol: 'LINK',
    precision: 18,
    // digits: ___________,
    // maxSell: ___________,
    name: 'Chainlink',
    icon: 'chainlink',
    // iconCircle: ___________,
    // iconColor: ___________,
    // ticker: ___________,
    // coinbaseTicker: ___________,
    color: '#3C5FCB',
    background: 'linear-gradient(90deg, #3C5FCB 0%, #0E319D 100%), #C4C4C4',
  },
  {
    symbol: 'GUSD',
    precision: 2,
    // digits: ___________,
    // maxSell: ___________,
    name: 'Gemini dollar',
    icon: 'gemini',
    // iconCircle: ___________,
    // iconColor: ___________,
    // ticker: ___________,
    // coinbaseTicker: ___________,
    // background: 'linear-gradient(90deg, #2FB1C8 0%, #69DCF6 100%), #C4C4C4',
    // color: '#69DCF6',
  },
  {
    symbol: 'ZRX',
    precision: 18,
    // digits: ___________,
    // maxSell: ___________,
    name: '0x',
    icon: 'zerox',
    // iconCircle: ___________,
    // iconColor: ___________,
    // ticker: ___________,
    // coinbaseTicker: ___________,
  },
  {
    symbol: 'USDC',
    precision: 6,
    digits: 6,
    digitsInstant: 2,
    maxSell: '1000000000000000',
    name: 'USD Coin',
    icon: 'usdc',
    // iconCircle: ___________,
    // iconColor: ___________,
    ticker: 'usdc-usd-coin',
  },
  {
    symbol: 'BAL',
    precision: 18,
    // digits: ___,
    digitsInstant: 2,
    // maxSell: ______,
    name: 'Balancer',
    icon: 'usdc',
    // iconCircle: ___________,
    // iconColor: ___________,
    // ticker: 'usdc-usd-coin',
  },
  {
    symbol: 'YFI',
    precision: 18,
    // digits: ___,
    digitsInstant: 2,
    // maxSell: ______,
    name: 'Yearn',
    icon: 'usdc',
    // iconCircle: ___________,
    // iconColor: ___________,
    // ticker: 'usdc-usd-coin',
  },
  // {
  //   symbol: 'WETH',
  //   precision: 18,
  //   digits: 5,
  //   maxSell: '10000000',
  //   name: 'Wrapped Ether',
  //   icon: AvatarSimple(ethSvg),
  //   // iconInverse: AvatarSimple(ethCircleSvg),
  //   iconCircle: AvatarSimple(ethCircleSvg),
  //   iconColor: AvatarSimple(ethCircleSvg),
  //   ticker: 'eth-ethereum',
  // },
  {
    symbol: 'DAI',
    precision: 18,
    digits: 4,
    maxSell: '10000000',
    name: 'Dai',
    icon: 'dai',
    iconCircle: 'dai_circle_color',
    iconColor: 'dai_color',
    ticker: 'dai-dai',
    coinbaseTicker: 'dai-usdc',
  },
  // {

  // },
  // {
  //   symbol: 'CHAI',
  //   precision: 18,
  //   digits: 4,
  //   maxSell: '10000000',
  //   name: 'Maker',
  //   icon: AvatarSimple(mkrSvg),
  //   iconCircle: AvatarSimple(mkrSvg),
  //   iconColor: AvatarSimple(mkrSvg),
  //   ticker: '',
  // },
  // {
  //   symbol: 'MKR',
  //   precision: 18,
  //   digits: 4,
  //   maxSell: '10000000',
  //   name: 'Maker',
  //   icon: AvatarSimple(mkrSvg),
  //   iconCircle: AvatarSimple(mkrSvg),
  //   iconColor: AvatarSimple(mkrSvg),
  //   ticker: 'usdc-usd-coin',
  // },
]

// ticker comes from coinpaprika api https://api.coinpaprika.com/v1/tickers
const tokensBySymbol = keyBy(tokens, 'symbol')

export function getToken(tokenSymbol: string) {
  if (!tokensBySymbol[tokenSymbol]) {
    console.warn('No token metadata for', tokenSymbol, 'using WETH!')
    return tokensBySymbol.ETH
  }
  return tokensBySymbol[tokenSymbol]
}
