export enum TxMetaKind {
  createDsProxy = 'createDsProxy',
  setProxyOwner = 'setProxyOwner',
  approve = 'approve',
  disapprove = 'disapprove',
  open = 'open',
  depositAndGenerate = 'depositAndGenerate',
  withdrawAndPayback = 'withdrawAndPayback',
  reclaim = 'reclaim',
  multiply = 'multiply',
  adjustPosition = 'adjustPosition',
  closeVault = 'closeVault',
  openGuni = 'openGuni',
  closeGuni = 'closeGuni',
  addTrigger = 'addTrigger',
  removeTrigger = 'removeTrigger',
  claimReward = 'claimReward',
  claimReferralFees = 'claimReferralFees',
}
