import { NetworkIds } from 'blockchain/networks'
import { LendingProtocol } from 'lendingProtocols'

export const depositTokensList = {
  [`${NetworkIds.MAINNET}-${LendingProtocol.AaveV3}`]: [
    'USDC',
    'DAI',
    'ETH',
    'WSTETH',
    'WBTC',
    'USDT',
    'SDAI',
    'RPL',
    'RETH',
    'LUSD',
    'AAVE',
    'CRV',
    'BAL',
    'MKR',
    'CBETH',
    'LDO',
    'LINK',
  ],
  [`${NetworkIds.OPTIMISMMAINNET}-${LendingProtocol.AaveV3}`]: [
    'ETH',
    'WBTC',
    'LINK',
    'SUSD',
    'RETH',
    'OP',
    'LUSD',
    'USDC',
    'USDT',
    'DAI',
  ],
  [`${NetworkIds.ARBITRUMMAINNET}-${LendingProtocol.AaveV3}`]: [
    'ETH',
    'WBTC',
    'USDC',
    'LINK',
    'ARB',
    'RETH',
    'LUSD',
    'USDT',
    'DAI',
  ],
  [`${NetworkIds.BASEMAINNET}-${LendingProtocol.AaveV3}`]: ['ETH', 'USDBC'],
  [`${NetworkIds.MAINNET}-${LendingProtocol.SparkV3}`]: [
    'USDC',
    'ETH',
    'WSTETH',
    'WBTC',
    'USDT',
    'RETH',
  ],
}
