import { ProductHubItem, ProductHubProductType } from 'features/productHub/types'
import { LendingProtocol } from 'lendingProtocols'

// network is added in the handler
export const makerProductHubProducts: Omit<ProductHubItem, 'network'>[] = [
  {
    product: [ProductHubProductType.Borrow, ProductHubProductType.Multiply],
    primaryToken: 'ETH',
    secondaryToken: 'DAI',
    protocol: LendingProtocol.Maker,
    label: 'ETH-A/DAI',
    multiplyStrategyType: 'long',
    multiplyStrategy: 'Long ETH',
  },
  {
    product: [ProductHubProductType.Borrow, ProductHubProductType.Multiply],
    primaryToken: 'ETH',
    secondaryToken: 'DAI',
    protocol: LendingProtocol.Maker,
    label: 'ETH-B/DAI',
    multiplyStrategyType: 'long',
    multiplyStrategy: 'Long ETH',
  },
  {
    product: [ProductHubProductType.Borrow, ProductHubProductType.Multiply],
    primaryToken: 'ETH',
    secondaryToken: 'DAI',
    protocol: LendingProtocol.Maker,
    label: 'ETH-C/DAI',
    multiplyStrategyType: 'long',
    multiplyStrategy: 'Long ETH',
  },
  {
    product: [ProductHubProductType.Borrow, ProductHubProductType.Multiply],
    primaryToken: 'WSTETH',
    primaryTokenGroup: 'ETH',
    secondaryToken: 'DAI',
    protocol: LendingProtocol.Maker,
    label: 'WSTETH-A/DAI',
    multiplyStrategyType: 'long',
    multiplyStrategy: 'Long WSTETH',
  },
  {
    product: [ProductHubProductType.Borrow, ProductHubProductType.Multiply],
    primaryToken: 'WSTETH',
    primaryTokenGroup: 'ETH',
    secondaryToken: 'DAI',
    protocol: LendingProtocol.Maker,
    label: 'WSTETH-B/DAI',
    multiplyStrategyType: 'long',
    multiplyStrategy: 'Long WSTETH',
  },
  {
    product: [ProductHubProductType.Borrow, ProductHubProductType.Multiply],
    primaryToken: 'RETH',
    primaryTokenGroup: 'ETH',
    secondaryToken: 'DAI',
    protocol: LendingProtocol.Maker,
    label: 'RETH-A/DAI',
    multiplyStrategyType: 'long',
    multiplyStrategy: 'Long RETH',
  },
  {
    product: [ProductHubProductType.Borrow, ProductHubProductType.Multiply],
    primaryToken: 'WBTC',
    secondaryToken: 'DAI',
    protocol: LendingProtocol.Maker,
    label: 'WBTC-A/DAI',
    multiplyStrategyType: 'long',
    multiplyStrategy: 'Long WBTC',
  },
  {
    product: [ProductHubProductType.Borrow, ProductHubProductType.Multiply],
    primaryToken: 'WBTC',
    secondaryToken: 'DAI',
    protocol: LendingProtocol.Maker,
    label: 'WBTC-B/DAI',
    multiplyStrategyType: 'long',
    multiplyStrategy: 'Long WBTC',
  },
  {
    product: [ProductHubProductType.Borrow, ProductHubProductType.Multiply],
    primaryToken: 'WBTC',
    secondaryToken: 'DAI',
    protocol: LendingProtocol.Maker,
    label: 'WBTC-C/DAI',
    multiplyStrategyType: 'long',
    multiplyStrategy: 'Long WBTC',
  },
  {
    product: [ProductHubProductType.Borrow],
    primaryToken: 'CRVV1ETHSTETH',
    secondaryToken: 'DAI',
    protocol: LendingProtocol.Maker,
    label: 'CRVV1ETHSTETH-A',
    multiplyStrategyType: 'long',
    multiplyStrategy: 'Long CRVV1ETHSTETH',
  },
  {
    product: [ProductHubProductType.Earn],
    primaryToken: 'DAI',
    secondaryToken: 'DAI',
    protocol: LendingProtocol.Maker,
    label: 'DSR',
    managementType: 'passive',
    earnStrategy: 'DSR',
  },
]
