on:
  push:
    branches:
      - gha-caching-testing

name: Docker AWS Test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1
      ECR_REPO_NAME: oasis-borrow-testing

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to ECR
      uses: docker/login-action@v1
      with:
        registry: ${{ steps.aws-credentials.outputs.aws-account-id }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

    - name: Extract commit hash
      id: vars
      shell: bash
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Build & Push image
      uses: docker/build-push-action@v2
      env:
        SHA_TAG: ${{ steps.vars.outputs.sha_short }}
        LATEST_TAG: latest
        ECR_REGISTRY: ${{ steps.aws-credentials.outputs.aws-account-id }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
        REPO_NAME: ${{ github.event.repository.name }}
      with:
        push: true
        build-args: |
            COMMIT_SHA=${{ env.SHA_TAG }}
            API_HOST=${{ secrets.API_HOST_STAGING }}
            MIXPANEL_ENV=staging
            MIXPANEL_KEY=${{ secrets.MIXPANEL_STAGING_KEY }}
            ADROLL_ADV_ID=${{ secrets.ADROLL_ADV_ID_STAGING }}
            ADROLL_PIX_ID=${{ secrets.ADROLL_PIX_ID_STAGING }}
            MAILCHIMP_ENDPOINT=${{ secrets.MAILCHIMP_ENDPOINT }}
            MAILCHIMP_API_KEY=${{ secrets.MAILCHIMP_API_KEY }}
            INFURA_PROJECT_ID=${{ secrets.INFURA_PROJECT_ID }}
            ETHERSCAN_API_KEY=${{ secrets.ETHERSCAN_API_KEY }}
            BLOCKNATIVE_API_KEY=${{ secrets.BLOCKNATIVE_STAGING_API_KEY }}
            SHOW_BUILD_INFO=1
            NODE_ENV=production
            NEXT_PUBLIC_SENTRY_ENV=development
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
        tags: |
          $ECR_REGISTRY/$ECR_REPO_NAME:$SHA_TAG
          $ECR_REGISTRY/$ECR_REPO_NAME:$LATEST_TAG
          $DOCKERHUB_ORG/$REPO_NAME:$SHA_TAG
          $DOCKERHUB_ORG/$REPO_NAME:$LATEST_TAG
        cache-from: type=gha
        cache-to: type=gha,mode=max
