# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: 'Next.js Bundle Analysis'

on:
  push:
    branches:
      - marcinciarka/next-bundle-analyze-workflow-fix-2
      - marcinciarka/sc-14044/fe-new-stop-loss-view-on-opening-a-position
  workflow_dispatch:

defaults:
  run:
    working-directory: ./

permissions:
  contents: read # for checkout repository
  actions: read # for fetching base branch bundle stats
  pull-requests: write # for comments

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.12
      - name: Use modules cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        env:
          CONFIG_URL: ${{ secrets.CONFIG_URL }}
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --no-progress --non-interactive --frozen-lockfile

      - name: Echo github event
        env:
          EVENT_OBJ: ${{ toJson(github.event) }}
        run: echo $EVENT_OBJ

      - name: Run postinstall
        env:
          CONFIG_URL: ${{ secrets.CONFIG_URL }}
        if: steps.yarn-cache.outputs.cache-hit == 'true'
        run: yarn postinstall

      - name: Use next cache
        uses: jongwooo/next-cache@v1

      - name: Build next.js app
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
          CONFIG_URL: ${{ secrets.CONFIG_URL }}
        run: yarn build

      # Here's the first place where next-bundle-analysis' own script is used
      # This step pulls the raw bundle stats for the current bundle
      - name: Analyze bundle
        run: npx -p nextjs-bundle-analysis report

      - name: Upload bundle
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: .next/analyze/__bundle_analysis.json

      - name: Download base branch bundle stats
        uses: dawidd6/action-download-artifact@v2
        if: always() && !failure() && !cancelled() && github.event.number
        with:
          workflow: nextjs_bundle_analysis.yml
          branch: ${{ github.event.pull_request.base.ref }}
          path: .next/analyze/base

      - name: Compare with base branch bundle
        if: always() && !failure() && !cancelled() && github.event.number
        run: ls -laR .next/analyze/base && npx -p nextjs-bundle-analysis compare

      - name: Get Comment Body
        id: get-comment-body
        if: always() && !failure() && !cancelled() && github.event.number
        run: |
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$(cat .next/analyze/__bundle_analysis_comment.txt)" >> $GITHUB_OUTPUT
          echo EOF >> $GITHUB_OUTPUT

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        if: always() && !failure() && !cancelled() && github.event.number
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          body-includes: '<!-- __NEXTJS_BUNDLE -->'

      - name: Create Comment
        uses: peter-evans/create-or-update-comment@v2
        if:
          ${{ !(failure() || cancelled()) && github.event.number && steps.fc.outputs.comment-id == 0
          }}
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.get-comment-body.outputs.body }}

      - name: Update Comment
        uses: peter-evans/create-or-update-comment@v2
        if:
          ${{ !(failure() || cancelled()) && github.event.number && steps.fc.outputs.comment-id == 0
          }}
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.get-comment-body.outputs.body }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
