name: Build Image from Pull Request.

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract commit hash
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Set up Docker Buildx
        id: buildex
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Cache Docker layers
        id: cache-layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx

      - name: Build, tag, and push image toDockerhub
        id: build-image
        uses: docker/build-push-action@v3
        env:
          SHA_TAG: ${{ steps.vars.outputs.sha_short }}
          LATEST_TAG: latest
          ENVIRONMENT_TAG: staging
          REPO_NAME: ${{ github.event.repository.name }}
          DOCKERHUB_ORG: "oasisdexorg"
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          build-args: |
            COMMIT_SHA=${{ env.SHA_TAG }}
            API_HOST=${{ secrets.API_HOST_STAGING }}
            MIXPANEL_ENV=staging
            MIXPANEL_KEY=${{ secrets.MIXPANEL_STAGING_KEY }}
            ADROLL_ADV_ID=${{ secrets.ADROLL_ADV_ID_STAGING }}
            ADROLL_PIX_ID=${{ secrets.ADROLL_PIX_ID_STAGING }}
            MAINNET_CACHE_URL=${{ secrets.MAINNET_CACHE_URL_STAGING }}
            MAILCHIMP_ENDPOINT=${{ secrets.MAILCHIMP_ENDPOINT }}
            MAILCHIMP_API_KEY=${{ secrets.MAILCHIMP_API_KEY }}
            INFURA_PROJECT_ID=${{ secrets.INFURA_PROJECT_ID }}
            ETHERSCAN_API_KEY=${{ secrets.ETHERSCAN_API_KEY }}
            BLOCKNATIVE_API_KEY=${{ secrets.BLOCKNATIVE_STAGING_API_KEY }}
            SHOW_BUILD_INFO=1
            NODE_ENV=production
            NEXT_PUBLIC_SENTRY_ENV=staging
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          tags: |
            ${{ env.DOCKERHUB_ORG }}/${{ env.REPO_NAME }}:${{ env.SHA_TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
            # Note the mode=max here
            # More: https://github.com/moby/buildkit#--export-cache-options
          # And: https://github.com/docker/buildx#--cache-tonametypetypekeyvalue
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
